---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: [prerequisites]

- name: Install system dependencies
  ansible.builtin.apt:
    name:
      - software-properties-common
      - curl
      - jq
      - iptables-persistent
      - libnetfilter-queue1
      - libnfnetlink0
      - net-tools
    state: present
    update_cache: true
  tags: [prerequisites]

- name: Load br_netfilter kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present
  tags: [prerequisites]

- name: Ensure br_netfilter loads on boot
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/br_netfilter.conf
    line: br_netfilter
    create: true
    owner: root
    group: root
    mode: "0644"
    state: present
  tags: [prerequisites]

- name: Configure kernel parameters for Docker bridge
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    sysctl_set: true
  loop:
    - name: net.bridge.bridge-nf-call-iptables
      value: "1"
    - name: net.bridge.bridge-nf-call-ip6tables
      value: "1"
  tags: [prerequisites]
