---
- name: Create Suricata rules directory
  ansible.builtin.file:
    path: /etc/suricata/rules
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: [configuration]

- name: Deploy Suricata main configuration
  ansible.builtin.template:
    src: suricata.yaml.j2
    dest: /etc/suricata/suricata.yaml
    owner: root
    group: root
    mode: '0644'
    backup: true
  tags: [configuration]

- name: Deploy custom rules
  ansible.builtin.template:
    src: local.rules.j2
    dest: /etc/suricata/rules/local.rules
    owner: root
    group: root
    mode: '0644'
    backup: true
  tags: [configuration]

- name: Set capabilities for Suricata
  ansible.builtin.command:
    cmd: setcap cap_net_admin,cap_net_raw+ep /usr/bin/suricata
  changed_when: false
  tags: [configuration]
